--------------------------------------------------------
--  File created - Friday-February-16-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INGREDIENTS
--------------------------------------------------------

  CREATE TABLE "PS8"."INGREDIENTS" 
   (	"ID" NUMBER(5,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"QUANTITY" NUMBER(3,0), 
	"UNIT" VARCHAR2(50 BYTE), 
	"CALORIES" NUMBER(5,0), 
	"ISMEAT" NUMBER(1,0), 
	"ISDAIRY" NUMBER(1,0), 
	"HASGLUTEN" NUMBER(1,0), 
	"HASFAT" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;
REM INSERTING into PS8.INGREDIENTS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index INGREDIENTS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PS8"."INGREDIENTS_PK" ON "PS8"."INGREDIENTS" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;
--------------------------------------------------------
--  Constraints for Table INGREDIENTS
--------------------------------------------------------

  ALTER TABLE "PS8"."INGREDIENTS" ADD CONSTRAINT "INGREDIENTS_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS"  ENABLE;
 
  ALTER TABLE "PS8"."INGREDIENTS" MODIFY ("ID" NOT NULL ENABLE);
