--------------------------------------------------------
--  File created - Friday-February-16-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table INGREDIENT_RECIPE_MAPPING
--------------------------------------------------------

  CREATE TABLE "PS8"."INGREDIENT_RECIPE_MAPPING" 
   (	"ID" NUMBER(5,0), 
	"RECIPEID" NUMBER(5,0), 
	"INGREDIENTID" NUMBER(5,0), 
	"ISVALID" NUMBER(1,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;
REM INSERTING into PS8.INGREDIENT_RECIPE_MAPPING
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index INGREDIENT_RECIPE_MAPPING_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PS8"."INGREDIENT_RECIPE_MAPPING_PK" ON "PS8"."INGREDIENT_RECIPE_MAPPING" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;
--------------------------------------------------------
--  Constraints for Table INGREDIENT_RECIPE_MAPPING
--------------------------------------------------------

  ALTER TABLE "PS8"."INGREDIENT_RECIPE_MAPPING" ADD CONSTRAINT "INGREDIENT_RECIPE_MAPPING_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS"  ENABLE;
 
  ALTER TABLE "PS8"."INGREDIENT_RECIPE_MAPPING" MODIFY ("ID" NOT NULL ENABLE);
