--------------------------------------------------------
--  File created - Friday-February-16-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table RECIPE
--------------------------------------------------------

  CREATE TABLE "PS8"."RECIPE" 
   (	"ID" NUMBER(6,0), 
	"NAME" VARCHAR2(50 BYTE), 
	"CHEFNAME" VARCHAR2(100 BYTE), 
	"COOKTIME" NUMBER(3,0), 
	"INSTRUCTION" CLOB, 
	"CUISINE" VARCHAR2(100 BYTE), 
	"LINK" VARCHAR2(100 BYTE), 
	"DIET" VARCHAR2(20 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" 
 LOB ("INSTRUCTION") STORE AS BASICFILE (
  TABLESPACE "CISETS" ENABLE STORAGE IN ROW CHUNK 8192 RETENTION 
  NOCACHE NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)) ;
REM INSERTING into PS8.RECIPE
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index RECIPE_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PS8"."RECIPE_PK" ON "PS8"."RECIPE" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;
--------------------------------------------------------
--  Constraints for Table RECIPE
--------------------------------------------------------

  ALTER TABLE "PS8"."RECIPE" ADD CONSTRAINT "RECIPE_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS"  ENABLE;
 
  ALTER TABLE "PS8"."RECIPE" MODIFY ("ID" NOT NULL ENABLE);
