--------------------------------------------------------
--  File created - Friday-February-16-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_ATTRIBUTES
--------------------------------------------------------

  CREATE TABLE "PS8"."USER_ATTRIBUTES" 
   (	"ID" NUMBER(3,0), 
	"USERID" NUMBER(6,0), 
	"ATTRIBUTEID" NUMBER(3,0), 
	"RECIPE_OR_INGREDIENT" VARCHAR2(1 BYTE), 
	"FAV_OR_ALLERGEN" VARCHAR2(1 BYTE)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;
REM INSERTING into PS8.USER_ATTRIBUTES
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index USER_ATTRIBUTES_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PS8"."USER_ATTRIBUTES_PK" ON "PS8"."USER_ATTRIBUTES" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;
--------------------------------------------------------
--  Constraints for Table USER_ATTRIBUTES
--------------------------------------------------------

  ALTER TABLE "PS8"."USER_ATTRIBUTES" MODIFY ("ID" NOT NULL ENABLE);
 
  ALTER TABLE "PS8"."USER_ATTRIBUTES" ADD CONSTRAINT "USER_ATTRIBUTES_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS"  ENABLE;
