--------------------------------------------------------
--  File created - Friday-February-16-2018   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table USER_DETAILS
--------------------------------------------------------

  CREATE TABLE "PS8"."USER_DETAILS" 
   (	"USERID" NUMBER(6,0), 
	"FNAME" VARCHAR2(20 BYTE), 
	"LNAME" VARCHAR2(20 BYTE), 
	"PASSWORD" VARCHAR2(50 BYTE), 
	"GENDER" VARCHAR2(10 BYTE), 
	"DOB" DATE, 
	"HEIGHT" NUMBER(2,0), 
	"WEIGHT" NUMBER(3,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS NOLOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;
REM INSERTING into PS8.USER_DETAILS
SET DEFINE OFF;
--------------------------------------------------------
--  DDL for Index USER_DETAILS_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PS8"."USER_DETAILS_PK" ON "PS8"."USER_DETAILS" ("USERID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS" ;
--------------------------------------------------------
--  Constraints for Table USER_DETAILS
--------------------------------------------------------

  ALTER TABLE "PS8"."USER_DETAILS" MODIFY ("USERID" NOT NULL ENABLE);
 
  ALTER TABLE "PS8"."USER_DETAILS" ADD CONSTRAINT "USER_DETAILS_PK" PRIMARY KEY ("USERID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 NOLOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "CISETS"  ENABLE;
